version: "3.8"
services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: db
    ports:
      - 1433:1433
    networks:
      - app-db-network
    volumes:
      - ./bookstore.sql:/docker-entrypoint-initdb.d/bookstore.sql 
    restart: unless-stopped
    tty: true
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
      MSSQL_SA_PASSWORD: "SecRet1~2#"
      MSSQL_VERSION: "2019"
      MSSQL_AGENT_ENABLE: "true"
      MSSQL_AGENT_AUTOSTART: "true"
      MSSQL_AGENT_STORAGE_PATH: "/var/opt/mssql/agent"
      MSSQL_AGENT_VERSION: "1.0.0"
      MSSQL_AGENT_POLLING_INTERVAL: "15"
      MSSQL_AGENT_PORT: "1433"
      MSSQL_AGENT_ENABLE_REMOTE_CONNECTIONS: "true"
      MSSQL_AGENT_ENABLE_REMOTE_CONNECTIONS_TO_DB: "true"
      MSSQL_AGENT_ENABLE_REMOTE_CONNECTIONS_TO_DB_PORT: "true"


  back-app:
    container_name: back-app
    image: scoma/espaceeducatiflara:latest
    ports:
      - 8000:8000
    depends_on:
      - db
    volumes:
      - app-volume:/app
    environment:
      APP_NAME: "espaceeducatiflara"
      APP_DEBUG: "false"
      APP_ENV: "prod"
      APP_KEY: "3ee69a49ba88d5db0c8086072b6c6b08" # :D
      APP_URL: "http://localhost:8000"
      DB_CONNECTION: "sqlsrv"
      DB_HOST: db
      DB_PORT: "1433"
      DB_DATABASE: "laravel"
      DB_USERNAME: "sa"
      DB_PASSWORD: "SecRet1~2#"
      MAIL_DRIVER: "smtp"
      MAIL_HOST: "smtp.mailtrap.io"
      MAIL_PORT: "2525"
      MAIL_USERNAME: "null"
      MAIL_PASSWORD: "null"
      MAIL_ENCRYPTION: "null"
      MAIL_FROM_ADDRESS: "null"
      MAIL_FROM_NAME: "espaceeducatiflara"
      MIX_PUSHER_APP_KEY: "${PUSHER_APP_KEY}"
      MIX_PUSHER_APP_CLUSTER: "${PUSHER_APP_CLUSTER}"


    networks:
      - app-db-network



  front-app:
    container_name: front-app
    image: scoma/espaceeducatifreact:latest
    ports:
      - 3000:3000
    depends_on:
      - back-app
    volumes:
      - app-volume:/app
    environment:
      APP_NAME: "espaceeducatiflara"
      API_HOST: "http://localhost:8000"
    networks:
      - app-db-network



volumes:
  db-volume:
    driver: local
  app-volume:
    driver: local

networks:
  app-db-network:
    driver: bridge